@ echo off
SET APPLICATION_FOLDER_MAIN=ak_sm_recorder
SET APPLICATION_FOLDER_OUT=ak_sm_recorder_f
SET GUI_PATH=gui_single_mode
SET APPLICATION_PATH=%~dp0

SET CONF_NAME=*.conf
SET PATH_FOLDER_RELATIVE_CONF=src\%APPLICATION_FOLDER_MAIN%\conf\
SET PATH_CONF_FILE=%APPLICATION_PATH%%PATH_FOLDER_RELATIVE_CONF%%CONF_NAME%
SET DESTINATION_FOLDER_RELATIVE_CONF=dist\%APPLICATION_FOLDER_OUT%\conf\
SET DESTINATION_FOLDER_ABSOLUTE_CONF=%APPLICATION_PATH%%DESTINATION_FOLDER_RELATIVE_CONF%


SET ASSETS_NAME=*.png
SET PAHT_FOLDER_RELATIVE_ASSETS=src\%GUI_PATH%\assets\
SET PATH_ASSETS_FILE=%APPLICATION_PATH%%PAHT_FOLDER_RELATIVE_ASSETS%%ASSETS_NAME%
SET DESTINATION_FOLDER_RELATIVE_ASSETS=dist\%APPLICATION_FOLDER_OUT%\%GUI_PATH%\assets\
SET DESTINATION_FOLDER_ABSOLUTE_ASSETS=%APPLICATION_PATH%%DESTINATION_FOLDER_RELATIVE_ASSETS%


ECHO %APPLICATION_PATH%
ECHO %PATH_CONF_FILE%
ECHO %DESTINATION_FOLDER_ABSOLUTE_CONF%
ECHO %PATH_ASSETS_FILE%
ECHO %DESTINATION_FOLDER_ABSOLUTE_ASSETS%


REM uncomment the following line if you need to generate again __main__.spec
REM pyi-makespec --paths=%APPLICATION_PATH%src\%APPLICATION_FOLDER_MAIN% --paths=%APPLICATION_FOLDER_MAIN%src\gui_frame_ext --paths=%APPLICATION_PATH%src\helpers %APPLICATION_PATH%src\%APPLICATION_FOLDER_MAIN%\__main__.py
pyinstaller win_exe_conf/__main__.spec ./src/%APPLICATION_FOLDER_MAIN%/__main__.py -y


REM copy .conf files to executable
MKDIR %DESTINATION_FOLDER_ABSOLUTE_CONF%
COPY %PATH_CONF_FILE% %DESTINATION_FOLDER_ABSOLUTE_CONF%

REM copy icons files
MKDIR %DESTINATION_FOLDER_ABSOLUTE_ASSETS%
COPY %PATH_ASSETS_FILE% %DESTINATION_FOLDER_ABSOLUTE_ASSETS%

cd dist
del %APPLICATION_FOLDER_OUT%.zip
"C:\Program Files\7-Zip\7z.exe" a -tzip %APPLICATION_FOLDER_OUT%
cd ..