@ echo off
REM HEADER FOR WINDOW SYSTEMS
REM Project: AK_SM_RECORDER Azure Kinect SM Recorder https://github.com/GRAP-UdL-AT/ak_sm_recorder
REM
REM  * PAgFRUIT http://www.pagfruit.udl.cat/en/
REM  * GRAP http://www.grap.udl.cat/
REM
REM  Author: Juan Carlos Miranda. https://github.com/juancarlosmiranda

SET APPLICATION_FOLDER_MAIN=ak_sm_recorder
SET APPLICATION_FOLDER_OUT=ak_sm_recorder_f
SET APPLICATION_PATH=%~dp0
SET DIST_FOLDER=dist
SET VERSION=1.2.1

SET CONF_NAME=*.conf
SET PAHT_FOLDER_RELATIVE_CONF=src\%APPLICATION_FOLDER_MAIN%\conf\
SET PATH_CONF_FILE=%APPLICATION_PATH%%PAHT_FOLDER_RELATIVE_CONF%%CONF_NAME%
SET DESTINATION_FOLDER_RELATIVE_CONF=dist\%APPLICATION_FOLDER_OUT%\conf
SET DESTINATION_FOLDER_ABSOLUTE_CONF=%APPLICATION_PATH%%DESTINATION_FOLDER_RELATIVE_CONF%


SET ASSETS_NAME=*.png
SET PAHT_FOLDER_RELATIVE_ASSETS=src\gui_frame_ext\assets\
SET PATH_ASSETS_FILE=%APPLICATION_PATH%%PAHT_FOLDER_RELATIVE_ASSETS%%ASSETS_NAME%
SET DESTINATION_FOLDER_RELATIVE_ASSETS=dist\%APPLICATION_FOLDER_OUT%\gui_frame_ext\assets\
SET DESTINATION_FOLDER_ABSOLUTE_ASSETS=%APPLICATION_PATH%%DESTINATION_FOLDER_RELATIVE_ASSETS%



ECHO %APPLICATION_PATH%
ECHO %PATH_CONF_FILE%
ECHO %DESTINATION_FOLDER_ABSOLUTE_CONF%

ECHO %PATH_ASSETS_FILE%
ECHO %DESTINATION_FOLDER_ABSOLUTE_ASSETS%

ECHO 'pip package is OK -- /dist/ak_frame_extractor_package-0.0.1-py3-none-any.whl'
rem -- INSTALL this modules to create PIP package
rem py -m pip install --upgrade pip
rem py -m pip install --upgrade build

py -m build

ECHO 'pip package is OK -- '/%DIST_FOLDER%/ak_frame_extractor_package-%VERSION%'-py3-none-any.whl
ECHO 'UPLOAD FOR TEST PACKAGE USING - twine upload --repository testpypi ./dist/*'
ECHO 'UPLOAD FINAL PACKAGE USING - twine upload ./dist/* --verbose'